[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
# linker
linker = "D:/tool_chains/embedded_toolchain/arm-gnu-toolchain-15.2.rel1-mingw-w64-i686-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc.exe"
# flags
rustflags = [
    "-C", "link-arg=-lgcc",  
    "-C", "target-feature=+crt-static"
]